var scanner;var activeCamera;var isQrCheckingActive=false;var SERVER="";var screens={LOGIN:1,LOGOUT:2,MAINMENU:3,SCANQR_ENTER:4,SCANQR_ENTER_PIN:5,SCANQR_EXIT:6,LISTSERVICES:7,SCANQR_USESERVICE:8,SCANQR_USESERVICE_PIN:9,CONFIRM_PAYMENT:10};var notificationStyles={SUCCESS:"success",INFO:"info",WARN:"warn",ERROR:"error"};var readQrData;var selectedPrice={};var currentScreen;var authorizingInterval;var REAUTHORIZE_TIME=1000*60*59;var darkMode=false;var styles;var hideVideoOnPage=false;var showRequestResultScreenInMilliseconds=4000;$(document).ready(function(){initLanguage();initStyle();initHideVideoOnPage();loadQrScanner();tryToAuthenticateAutomatically();assignAction();});function initLanguage(){var savedLang=getStoredData("LANG");changeLanguage(savedLang);}
function changeLanguage(lang){switch(lang){case"hu":current_lang_index=1;break;default:current_lang_index=0;current_lang=langs[current_lang_index];break;}
current_lang=langs[current_lang_index];setStoredData("LANG",current_lang);translate();}
function translate(){$("[data-translate]").each(function(){var key=$(this).data('translate');$(this).html(getTranslationForCurrentLanguage(key));});$("[data-translatebtn]").each(function(){var key=$(this).data('translatebtn');$(this).val(getTranslationForCurrentLanguage(key));});}
function getTranslationForCurrentLanguage(key){return dictionary[current_lang][key]||"N/A";}
function initHideVideoOnPage(){var storedHideVideoOnPage=getStoredData("HIDEVIDEO");if(storedHideVideoOnPage=="true"){hideVideoOnPage=true;$("#preview").hide();$("#hideVideoPreview").val(getTranslationForCurrentLanguage("displayVideoPreview"));$("#qrPic").show();}else{hideVideoOnPage=false;$("#preview").show();$("#hideVideoPreview").val(getTranslationForCurrentLanguage("hideVideoPreview"));$("#qrPic").hide();}
setStoredData("HIDEVIDEO",hideVideoOnPage);}
function tryToAuthenticateAutomatically(){var terminalReferenceNumber=getTerminalRefNumberFromToken();if(terminalReferenceNumber==""){removeStoredData('Authorization');changeScreenLogin();}else{var url=SERVER+"/qrsys/rest/rpi/reauthorize";var req={};req.terminalReferenceNumber=terminalReferenceNumber;sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},null,function(xhr){if(xhr.status==200){var token=xhr.getResponseHeader("Authorization");if(token){setStoredData("Authorization",token);}
startBackGroundReAuthorizing();changeScreenMenu();}else{removeStoredData('Authorization');changeScreenLogin();}});}}
function getTerminalRefNumberFromToken(){var token=getStoredData("Authorization");if(token==null||token==""){return"";}else{try{var decoded=jwt_decode(token);return decoded.terminal;}catch(e){return"";}}}
function initStyle(){styles={light:"<style id='light'>body { color: black; background-color: white;} </style>",dark:"<style id='dark'>body { color: white; background-color: black;} </style>"};var useDarkTheme=getStoredData("DARKTHEME");if(useDarkTheme==""){$("head").append(styles.light);darkMode=false;setStoredData("DARKTHEME",darkMode);}else if(useDarkTheme=="true"){$("head").append(styles.dark);darkMode=true;}else{$("head").append(styles.light);darkMode=false;}}
function switchToTheOtherStyle(){if(darkMode){$("#dark").remove();$("head").append(styles.light);}else{$("#light").remove();$("head").append(styles.dark);}
darkMode=!darkMode;setStoredData("DARKTHEME",darkMode);}
function hideAllExcept(divId,menuVisible){$('#terminalWrapper div').not("#"+divId).hide();$("#"+divId).show();$("#themeChoosing").show();if(menuVisible){$("#terminalMenuBackButton").show();}else{$("#terminalMenuBackButton").hide();}}
function assignAction(){$("#loginBtn").click(function(e){e.preventDefault();app_login($("#loginQr").val(),$("#loginPass").val(),$("#loginRefnum").val());});$("#exitBtn").click(function(e){e.preventDefault();changeScreenExit();});$("#logoutBtn").click(function(e){e.preventDefault();if(confirm(getTranslationForCurrentLanguage("logoutTerminalQuestion"))){app_logout();}});$("#enterBtn").click(function(e){e.preventDefault();changeScreenEnter();});$("#szolgBtn").click(function(e){e.preventDefault();changeScreenServicesList();});$("#enterSubmit").click(function(e){e.preventDefault();app_sendEnterRequest(readQrData,$("#enterPass").val());});$("#serviceUseSubmit").click(function(e){e.preventDefault();app_useService(readQrData,$("#serviceUsePass").val());});$("#backToMenu").click(function(e){e.preventDefault();changeScreenMenu();});$("#hideVideoPreview").click(function(e){e.preventDefault();changeHideOrDisplayVideoPreview();});$("#setOtherTheme").click(function(e){e.preventDefault();switchToTheOtherStyle();});$("#btYes").click(function(e){e.preventDefault();changeScreenServicesEnterPin();});$("#btNo").click(function(e){e.preventDefault();changeScreenServicesScanForQr();});$("#huSelected").click(function(e){e.preventDefault();changeLanguage("hu");});$("#enSelected").click(function(e){e.preventDefault();changeLanguage("en");});}
function changeHideOrDisplayVideoPreview(){if(!hideVideoOnPage){$("#preview").hide();hideVideoOnPage=true;$("#hideVideoPreview").val(getTranslationForCurrentLanguage("displayVideoPreview"));$("#qrPic").show();}else{$("#preview").show();hideVideoOnPage=false;$("#hideVideoPreview").val(getTranslationForCurrentLanguage("hideVideoPreview"));$("#qrPic").hide();}
setStoredData("HIDEVIDEO",hideVideoOnPage);}
function assignServicesListClickers(){$('.clicker').click(function(){$(this).nextUntil('.clicker').slideToggle('normal');});$("tr[id^='p']").each(function(){$(this).click(function(){selectedPrice.id=$(this).attr("id").substring(1);selectedPrice.description=$(this).find(':first-child').text();selectedPrice.amount=$(this).find("td:nth-child(2)").text();;changeScreenServicesScanForQr();});});}
function loadQrScanner(){scanner=new Instascan.Scanner({video:document.getElementById('preview')});scanner.addListener('scan',function(content){showProcessingScreen();readQrData=content;switch(currentScreen){case screens.SCANQR_ENTER:app_sendEnterRequest(content,"");break;case screens.SCANQR_EXIT:app_exit(content);break;case screens.SCANQR_USESERVICE:changeScreenConfirmPayment(selectedPrice.amount,selectedPrice.description);break;}});Instascan.Camera.getCameras().then(function(cameras){if(cameras.length>0){activeCamera=cameras[0];}else{console.error('No cameras found.');}}).catch(function(e){console.error(e);});}
function emptyAllInputBoxValues(){$("#loginRefnum").val("");$("#loginQr").val("");$("#loginPass").val("");$("#enterPass").val("");$("#serviceUsePass").val("");}
function startQrScanner(){if(!isQrCheckingActive){scanner.start(activeCamera);isQrCheckingActive=true;}}
function stopQrScanner(){if(isQrCheckingActive){scanner.stop(activeCamera);isQrCheckingActive=false;}}
function changeScreenLogin(){hideAllExcept("terminalLoginScreen",false);currentScreen=screens.LOGIN;stopQrScanner();selectedPrice={};readQrData="";emptyAllInputBoxValues();}
function changeScreenMenu(){stopQrScanner();hideAllExcept("terminalMenuScreen",false);currentScreen=screens.MAINMENU;readQrData="";selectedPrice={};emptyAllInputBoxValues();}
function changeScreenLogout(){changeScreenLogin();}
function changeScreenEnter(){startQrScanner();hideAllExcept("qrScanPreview",true);currentScreen=screens.SCANQR_ENTER;readQrData="";}
function changeScreenEnterPin(){stopQrScanner();emptyAllInputBoxValues();hideAllExcept("terminalEnterScreen",true);currentScreen=screens.SCANQR_ENTER_PIN;}
function changeScreenExit(){startQrScanner();hideAllExcept("qrScanPreview",true);currentScreen=screens.SCANQR_EXIT;readQrData="";}
function changeScreenServicesList(){stopQrScanner();hideAllExcept("terminalPaidServicesScreen",true);currentScreen=screens.LISTSERVICES;selectedPrice={};app_services();}
function changeScreenServicesScanForQr(){startQrScanner();hideAllExcept("qrScanPreview",true);currentScreen=screens.SCANQR_USESERVICE;readQrData="";emptyAllInputBoxValues();}
function changeScreenServicesEnterPin(){stopQrScanner();hideAllExcept("terminalUseServiceScreen",true);currentScreen=screens.SCANQR_USESERVICE_PIN;}
function changeScreenConfirmPayment(price,description){stopQrScanner();hideAllExcept("dialog",false);$("#confirmPayment").html(getTranslationForCurrentLanguage("areYouSureYouWantToPay")
+" "+price+" : "+description+"?");currentScreen=screens.CONFIRM_PAYMENT;}
function showProcessingScreen(){showNotification(getTranslationForCurrentLanguage("processingPleaseWait"),notificationStyles.INFO);stopQrScanner();hideAllExcept("pleaseWaitScreen",false);}
function showNotification(message,style){$("#pleaseWaitText").removeClass();$("#pleaseWaitText").addClass(style);$("#pleaseWaitText").html(message);}
function app_login(qr,pass,ref){showProcessingScreen();var url=SERVER+"/qrsys/rest/rpi/terminallogin";var req={};req.qrCode=qr;req.pin=pass;req.terminalReferenceNumber=ref;sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){setStoredData("Authorization",xhr.getResponseHeader("Authorization"));var message=getTranslationForCurrentLanguage("terminalLoginSuccessful");showNotification(message,notificationStyles.SUCCESS);setTimeout(function(){changeScreenMenu();},showRequestResultScreenInMilliseconds);startBackGroundReAuthorizing();},function(xhr){checkError(xhr);setTimeout(function(){changeScreenLogin();},showRequestResultScreenInMilliseconds);});}
function app_logout(){showProcessingScreen();var url=SERVER+"/qrsys/rest/rpi/terminallogout";var req={};req.terminalReferenceNumber=getTerminalRefNumberFromToken();if(req.terminalReferenceNumber==""){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){var message=xhr.responseJSON.referenceNumber+" "
+getTranslationForCurrentLanguage("terminalLoggedOutSuccessfully");showNotification(message,notificationStyles.SUCCESS);removeStoredData('Authorization');stopBackGroundReAuthorizing();},function(xhr){checkError(xhr);});setTimeout(function(){changeScreenLogout();},showRequestResultScreenInMilliseconds);}}
function checkError(xhr){if(xhr!=undefined&&xhr!=null&&xhr.responseJSON!=null&&xhr.responseJSON!=undefined){var message=xhr.responseJSON.localizedMessage;showNotification(message,notificationStyles.ERROR);}else{var message=getTranslationForCurrentLanguage("errorHappenedTryAgainLater");showNotification(message,notificationStyles.ERROR);}}
function app_sendEnterRequest(qr,pass){showProcessingScreen();var url=SERVER+"/qrsys/rest/rpi/enter";var req={};req.qrCode=qr;req.pin=pass;req.terminalReferenceNumber=getTerminalRefNumberFromToken();if(req.terminalReferenceNumber==""){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){var message=getTranslationForCurrentLanguage("welcome")+" "
+xhr.responseJSON.accountData.firstName
+" "+xhr.responseJSON.accountData.lastName+"! "
+getTranslationForCurrentLanguage("youCanEnter");showNotification(message,notificationStyles.SUCCESS);setStoredData("Authorization",xhr.getResponseHeader("Authorization"));setTimeout(function(){changeScreenEnter();},showRequestResultScreenInMilliseconds);},function(xhr){if(xhr!=null&&xhr!=undefined&&xhr.responseJSON!=null&&xhr.responseJSON!=undefined&&xhr.responseJSON.errorCode==42){changeScreenEnterPin();}else{checkError(xhr);setTimeout(function(){changeScreenEnter();},showRequestResultScreenInMilliseconds);}});}}
function app_exit(qr){showProcessingScreen();var url=SERVER+"/qrsys/rest/rpi/exit";var req={};req.qrCode=qr;req.terminalReferenceNumber=getTerminalRefNumberFromToken();if(req.terminalReferenceNumber==""){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){var message=getTranslationForCurrentLanguage("goodbye")+" "
+xhr.responseJSON.accountData.firstName
+" "+xhr.responseJSON.accountData.lastName+"! "
+getTranslationForCurrentLanguage("exitSuccessful");showNotification(message,notificationStyles.SUCCESS);setStoredData("Authorization",xhr.getResponseHeader("Authorization"));setTimeout(function(){changeScreenExit();},showRequestResultScreenInMilliseconds);},function(xhr){checkError(xhr);setTimeout(function(){changeScreenExit();},showRequestResultScreenInMilliseconds);});}}
function app_services(){$('#servicelist').empty();var url=SERVER+"/qrsys/rest/rpi/paidservices";var token=getStoredData("Authorization");if(token==""||token==null){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("GET",url,null,function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){setStoredData("Authorization",xhr.getResponseHeader("Authorization"));var serviceList=xhr.responseJSON;for(var i=0;i<serviceList.length;i++){var newServiceWithPrices="<tr class=\"clicker\" id=\"s"+serviceList[i].id
+"\"><td colspan=\"2\">"
+serviceList[i].title+"</td></tr>";for(var j=0;j<serviceList[i].prices.length;j++){currentPriceRow="<tr class=\"bg-primary\" id=\"p"+serviceList[i].prices[j].id
+"\" style=\"display: none;\"><td>"+serviceList[i].prices[j].description+"</td><td>"+(-serviceList[i].prices[j].amount)+"</td></tr>";newServiceWithPrices+=currentPriceRow;}
$('#servicelist').append("<tbody>"+newServiceWithPrices+"</tbody>");}
assignServicesListClickers();},function(xhr){});}}
function app_useService(qr,pass){showProcessingScreen();var url=SERVER+"/qrsys/rest/rpi/useservice";var req={};req.qrCode=qr;req.pin=pass;req.priceId=selectedPrice.id;req.terminalReferenceNumber=getTerminalRefNumberFromToken();if(req.terminalReferenceNumber==""){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},function(data,textStatus,xhr){var message=getTranslationForCurrentLanguage("usingServiceSuccessSentence1")
+" "
+xhr.responseJSON.priceDescription
+" "
+getTranslationForCurrentLanguage("usingServiceSuccessSentence2")
+" "
+xhr.responseJSON.firstName+" "+xhr.responseJSON.lastName
+"!";showNotification(message,notificationStyles.SUCCESS);setStoredData("Authorization",xhr.getResponseHeader("Authorization"));setTimeout(function(){changeScreenServicesScanForQr();},showRequestResultScreenInMilliseconds);},function(xhr){checkError(xhr);setTimeout(function(){changeScreenServicesScanForQr();},showRequestResultScreenInMilliseconds);});}}
function startBackGroundReAuthorizing(){authorizingInterval=setInterval(reAuthorize,REAUTHORIZE_TIME);}
function stopBackGroundReAuthorizing(){clearInterval(authorizingInterval);}
function reAuthorize(){console.log("Reauthorizing.");var url=SERVER+"/qrsys/rest/rpi/reauthorize";var req={};req.terminalReferenceNumber=getTerminalRefNumberFromToken();if(req.terminalReferenceNumber==""){changeScreenLogin();removeStoredData('Authorization');}else{sendAjax("POST",url,JSON.stringify(req),function(xhr){xhr.setRequestHeader('Authorization',getStoredData("Authorization"));xhr.setRequestHeader('Content-Language',current_lang);},null,function(xhr){var token=xhr.getResponseHeader("Authorization");if(token){setStoredData("Authorization",token);}});}}
function setCookie(cname,cvalue,exdays){var expires="";if(cvalue!=0&&cvalue!="0"){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));expires="expires="+d.toUTCString()+";";}
document.cookie=cname+"="+cvalue+";"+expires+"path=/";}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";}
function delete_cookie(name){document.cookie=name+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';}
function setStoredData(name,value){localStorage.setItem(name,value);}
function getStoredData(name){return localStorage.getItem(name);}
function removeStoredData(name){localStorage.removeItem(name)}
function removeAllStoredDataForThisWebsite(){localStorage.clear();}